#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${SCRIPT_DIR}/../src"

COLORS_FILE="${SRC_DIR}/colors.h"
SHAPE_FILE="${SRC_DIR}/shape.h"

# Skip generation when files already exist to preserve local customizations.
if [[ -f "$COLORS_FILE" && -f "$SHAPE_FILE" ]]; then
  exit 0
fi

declare -A bg=(
  [1]="#0a0f2d"
  [2]="#251b4b"
  [3]="#7d2ff7"
  [4]="#f78fb3"
)

declare -A fg=(
  [dis]="#8ce9ff"
  [ker]="#ff7edb"
  [upt]="#ffd8ff"
  [mem]="#ffd6a5"
  [pipe]="#b3f4ff"
)

hex_to_rgb() {
  local hex="${1#\#}"
  printf "%d;%d;%d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

cat > "$COLORS_FILE" <<EOF
/* colors.h - generated by scripts/gen-default-assets.sh */
#ifndef GLITCH_COLORS_H
#define GLITCH_COLORS_H

#define ESC       "\e"
#define CSI       ESC "["

#define F_RESET   CSI "0m"

#define BG1       CSI "48;2;$(hex_to_rgb "${bg[1]}")m"
#define BG2       CSI "48;2;$(hex_to_rgb "${bg[2]}")m"
#define BG3       CSI "48;2;$(hex_to_rgb "${bg[3]}")m"
#define BG4       CSI "48;2;$(hex_to_rgb "${bg[4]}")m"

#define FG_DIS    CSI "38;2;$(hex_to_rgb "${fg[dis]}")m"
#define FG_KER    CSI "38;2;$(hex_to_rgb "${fg[ker]}")m"
#define FG_UPT    CSI "38;2;$(hex_to_rgb "${fg[upt]}")m"
#define FG_MEM    CSI "38;2;$(hex_to_rgb "${fg[mem]}")m"
#define FG_PIPE   CSI "38;2;$(hex_to_rgb "${fg[pipe]}")m"

#endif
EOF

cat > "$SHAPE_FILE" <<'EOF'
/* shape.h - generated by scripts/gen-default-assets.sh */
#ifndef GLITCH_SHAPE_H
#define GLITCH_SHAPE_H

/*  WIDE GENTOO SWIRL (4 lines tall, fixed-width rows) */

/* Base shape (all rows are 39 chars wide) */

#define SHAPE1    "        ___------_______               "
#define SHAPE2    "    ____/   .-.    .-.   \____         "
#define SHAPE3    "  _/  _  \  (   )  (   )  /  _  \_     "
#define SHAPE4    "  \______/\__\_/____\_/__/\______/     "

/*
 * For stable colors:
 *  - We only glitch rows 1, 3, 4 (SHAPE1/3/4_S*)
 *  - Row 2 (SHAPE2_S*) is forced to match SHAPE2 exactly,
 *    so the 'ker |' column never moves horizontally.
 */

/* Glitch phases for row 1 */

#define SHAPE1_S1 "        _--~~~---______               "
#define SHAPE1_S2 "        ___------______               "
#define SHAPE1_S3 "        ___------_______              "

/* Row 2: keep ALL glitch variants identical to SHAPE2 for alignment */

#define SHAPE2_S1 SHAPE2
#define SHAPE2_S2 SHAPE2
#define SHAPE2_S3 SHAPE2

/* Glitch phases for row 3 */

#define SHAPE3_S1 "  _/  _  \  (  _)(   )  /  _  \_     "
#define SHAPE3_S2 "  _/  _  \  (_  ) ( _ )  /  _  \_    "
#define SHAPE3_S3 "  _/  _  \  (   )  (   )  /  _  \_   "

/* Glitch phases for row 4 */

#define SHAPE4_S1 "  \______/\__\_/ _--\_/__/\______/    "
#define SHAPE4_S2 "  \______/\__\_/-___\_/__/\______/    "
#define SHAPE4_S3 "  \______/\__\_/____\_/__/\______/    "

#endif
EOF

echo "Generated default colors.h and shape.h in ${SRC_DIR}" >&2
