/* colors.h - generated by install.sh */
#ifndef GLITCH_COLORS_H
#define GLITCH_COLORS_H

#define ESC       "\e"
#define CSI       ESC "["

#define F_RESET   CSI "0m"

#define BG1       CSI "48;2;24;52;72m"
#define BG2       CSI "48;2;31;70;103m"
#define BG3       CSI "48;2;160;51;109m"
#define BG4       CSI "48;2;175;86;113m"

#define FG_DIS    CSI "38;2;128;143;154m"
#define FG_KER    CSI "38;2;132;153;171m"
#define FG_UPT    CSI "38;2;203;143;175m"
#define FG_MEM    CSI "38;2;211;162;177m"
#define FG_PIPE   CSI "38;2;128;143;154m"

#endif
